// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhm-PvJwrdT8I2D-ldr04AauMvtXD4tk0',
    appId: '1:1092183300444:web:e3ce44d22adf07d7148999',
    messagingSenderId: '1092183300444',
    projectId: 'term-project-5f334',
    authDomain: 'term-project-5f334.firebaseapp.com',
    storageBucket: 'term-project-5f334.firebasestorage.app',
    measurementId: 'G-ED1MBLCXE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmviuiU4teuUpSniucixJx4GApfsRkZmM',
    appId: '1:1092183300444:android:4942b731150a63f6148999',
    messagingSenderId: '1092183300444',
    projectId: 'term-project-5f334',
    storageBucket: 'term-project-5f334.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpfeieMWt9LxpxAGTWBSApirknizJlRQs',
    appId: '1:1092183300444:ios:f7e108d4f21e1cdb148999',
    messagingSenderId: '1092183300444',
    projectId: 'term-project-5f334',
    storageBucket: 'term-project-5f334.firebasestorage.app',
    iosBundleId: 'com.example.termProjectProjGomez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpfeieMWt9LxpxAGTWBSApirknizJlRQs',
    appId: '1:1092183300444:ios:f7e108d4f21e1cdb148999',
    messagingSenderId: '1092183300444',
    projectId: 'term-project-5f334',
    storageBucket: 'term-project-5f334.firebasestorage.app',
    iosBundleId: 'com.example.termProjectProjGomez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhm-PvJwrdT8I2D-ldr04AauMvtXD4tk0',
    appId: '1:1092183300444:web:16b9f9b25ff84413148999',
    messagingSenderId: '1092183300444',
    projectId: 'term-project-5f334',
    authDomain: 'term-project-5f334.firebaseapp.com',
    storageBucket: 'term-project-5f334.firebasestorage.app',
    measurementId: 'G-GLN1ZRQ865',
  );
}
